gestionMedProj/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import medicaments

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('medicaments.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

admin.site.site_header="APPMed"
admin.site.site_title="APPMed"
admin.site.index_title=""

medicaments/urls.py
from django.contrib import admin
from django.urls import path
from .views import DmmCreateView, DmmListView, DmmUpdateView, InventaireProduitListView, InventaireCreateView, InventaireUpdateView, LivraisonUpdateView, ProduitCreateView,ProduitListView, delete_commande, delete_inventaire, get_ajax_dernier_six_mois, get_ajax_gauge, get_ajax_msd_produit, home,home_dmm,CommandeCreateView,CommandeListView,CommandeUpdateView,BonLivraisonCreateView,LivraisonListView,LivraisonUpdateView,SortieCreateView,SortieListView,SortieUpdateView,InventaireListView,ProduitUpdateView,produit_delete,sortie_delete,livraison_delete,get_products_ajax,get_ajax_line,delete_dmm

urlpatterns = [
   path('', home,name='home'), 
   
    #########produits URL ####
    path('produits/', ProduitListView.as_view(),name='produit_list'),  
    path('produits/create', ProduitCreateView.as_view(),name='produit_form'),
    path('produits/<int:pk>/update', ProduitUpdateView.as_view(),name='produit_update'),
    path('produits/<int:pk>/delete', produit_delete,name='produit_delete'),
    path('produits/api/msd_produit/', get_ajax_msd_produit,name='get_ajax_msd_produit'),
    path('produits/api/gauge_produit/', get_ajax_gauge,name='get_ajax_gauge'),  
    path('produits/api/dmm_produit/', get_ajax_line,name='get_ajax_line'), 
   
   
    path('<int:categorie>', home,name='home'),
    path('dmm/<int:categorie>', home_dmm,name='home_dmm'),#dashbord page for dmm
    path('commandes/create', CommandeCreateView.as_view(),name='commande_form'),
    path('commandes/<int:pk>/update', CommandeUpdateView.as_view(),name='commande_update'),   
    path('commandes/<int:pk>/delete', delete_commande,name='delete_commande'),    
    path('commandes/list', CommandeListView.as_view(),name='commande_list'),  
      
    
    path('commandes/get_products_ajax', get_products_ajax,name='get-products-ajax'),
    ####livraison url
    path('livraison/create',BonLivraisonCreateView.as_view(),name='livraison_form'),
    path('livraison/list', LivraisonListView.as_view(),name='livraison_list'), 
    path('livraison/<int:pk>/update', LivraisonUpdateView.as_view(),name='livraison_update'),   
    path('livraison/<int:pk>/delete', livraison_delete,name='livraison_delete'),   
    ####sortie url 
    path('sortie/create',SortieCreateView.as_view(),name='sortie_form'),
    path('sortie/list', SortieListView.as_view(),name='sortie_list'), 
    path('sortie/<int:pk>/update', SortieUpdateView.as_view(),name='sortie_update'),   
    path('sortie/<int:pk>/delete', sortie_delete,name='sortie_delete'),
    #########Inventaire urls
    path('inventaires/create', InventaireCreateView.as_view(),name='inventaire_form'),
    path('inventaires/<int:pk>/update', InventaireUpdateView.as_view(),name='inventaire_update'),   
    path('inventaires/<int:pk>/delete', delete_inventaire,name='delete_inventaire'),    
    path('inventaires/list', InventaireListView.as_view(),name='inventaire_list'),  
    path('inventaires/<int:produit_id>/<int:mois>/<int:annee>', InventaireProduitListView.as_view(),name='inventaire_produit_list'),


    path('params/dmm', DmmListView.as_view(),name='dmm_list'), 
    path('params/dmm/create', DmmCreateView.as_view(),name='dmm_form'), 
    path('params/dmm/get_ajax_dernier_six_mois', get_ajax_dernier_six_mois,name='get-ajax-dernier-six-mois'),
    path('params/dmm/<int:pk>/update', DmmUpdateView.as_view(),name='dmm_update'), 
    path('params/dmm/<int:pk>/delete', delete_dmm,name='delete_dmm'),
    
]

medicaments/models.py
#from asyncio.windows_events import NULL
from email.policy import default
from gettext import NullTranslations

#from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Categorie(models.Model):
    CATEGORIE_CHOICES = (
        ('medicament','medicament'),
        ('test_rapid','test rapide'),
        ('reactif','reactif'),
        ('preservatif','preservatif'),
       
    )
    nom = models.CharField(max_length=255,verbose_name='categorie')
    def __str__(self):
        return self.nom
#classification:eg. ARV adulte,etc. 
class Classification(models.Model):
    
    nom = models.CharField(max_length=255,verbose_name='classification')
    def __str__(self):
        return self.nom
    
class Programme(models.Model):
    CATEGORIE_CHOICES = (
        ('vih','VIH'),
        ('tb','TB'),
        ('malaria','Malaria'),
        
       
    )
    nom = models.CharField(max_length=255,verbose_name='programme')
    def __str__(self):
        return self.nom
class Dosage(models.Model):
    nom = models.CharField(max_length=255,verbose_name='dosage')
    def __str__(self):
        return self.nom
class Formulation(models.Model):
    nom = models.CharField(max_length=255,verbose_name='formulation')
    def __str__(self):
        return self.nom
class Conditionnement(models.Model):
    nom = models.CharField(max_length=255,verbose_name='conditionnement')
    def __str__(self):
        return self.nom

class Produit(models.Model):
    designation = models.CharField(max_length=500,verbose_name='desigantion')
    abbreviation = models.CharField(max_length=255,verbose_name='abreviation',default='',null=True)
    num_ref = models.CharField(max_length=255,verbose_name='Num Ref',null=True,blank=True)
    #taille_paquet = models.PositiveIntegerField(default=1)
    dosage = models.ForeignKey(Dosage,on_delete=models.SET_NULL,verbose_name='dosage',null=True,blank=True)
    formulation = models.ForeignKey(Formulation,on_delete=models.SET_NULL,verbose_name='formulation',null=True,blank=True)
    conditionnement = models.ForeignKey(Conditionnement,on_delete=models.SET_NULL,verbose_name='conditionnement',null=True,blank=True)
    categorie = models.ForeignKey(Categorie,on_delete=models.PROTECT,verbose_name='categorie')
    classification = models.ForeignKey(Classification,on_delete=models.PROTECT,verbose_name='classification',null=True,blank=True)

    programme = models.ForeignKey(Programme,on_delete=models.PROTECT,verbose_name='programme',default=1)
    dashbord = models.BooleanField(default=0)
    class Meta:
        ordering =['designation']
    def __str__(self):
        return f"{self.designation}"
class CoutUnitaire(models.Model):
    cout = models.PositiveIntegerField(verbose_name="Cout unitaire USD$")
    date_debut = models.DateField(verbose_name = "Date debut")
    date_fin = models.DateField(verbose_name = "Date fin")
    produit = models.ForeignKey(Produit,on_delete=models.CASCADE)

class ConsMoy(models.Model):
    class Meta:
        verbose_name ="Besoin annuel previsionnel"
    ANNEE_CHOICES =(
        (2022,2022),
        (2021,2021),
        (2020,2020),
    )
    produit = models.ForeignKey(Produit,on_delete=models.CASCADE,verbose_name='produit')
    annee = models.PositiveIntegerField(verbose_name='annee',choices=ANNEE_CHOICES)
    value = models.PositiveIntegerField(verbose_name='cons. moyenne annuel')
    def __str__(self):
        return f"{self.produit} - ({round(int(self.value)/12,0)})"


class ConsMoyReel(models.Model):
    ANNEE_CHOICES =(
        (2022,2022),
        (2021,2021),
        (2020,2022),
    )
    MOIS_CHOICES = (
        ('01','janvier'),
        ('02','Fevrier'),
        ('03','Mars'),
        ('04','Avril'),
        ('05','Mai'),
        ('06','Juin'),
        ('07','Juillet'),
        ('08','Aout'),
        ('09','Septembre'),
        ('10','Octobre'),
        ('11','Novembre'),
        ('12','Decembre'),

    )
    produit = models.ForeignKey(Produit,on_delete=models.CASCADE,verbose_name='produit')
    annee = models.PositiveIntegerField(verbose_name='annee',choices=ANNEE_CHOICES)
    mois = models.PositiveIntegerField(verbose_name='mois',choices=MOIS_CHOICES)
    value = models.PositiveIntegerField(verbose_name='cons. moyenne mens. reel')
    def __str__(self):
        return f"{self.produit} - ({int(self.value)})"

class DistrMoy(models.Model):
    class Meta:
        verbose_name ="Distribution Moyenne  Men"
    ANNEE_CHOICES =(
        (2022,2022),
        (2021,2021),
        (2020,2020),
    )
    MOIS_CHOICES = (
        (1,'janvier'),
        (2,'Fevrier'),
        (3,'Mars'),
        (4,'Avril'),
        (5,'Mai'),
        (6,'Juin'),
        (7,'Juillet'),
        (8,'Aout'),
        (9,'Septembre'),
        (10,'Octobre'),
        (11,'Novembre'),
        (12,'Decembre'),

    )
    
    produit = models.ForeignKey(Produit,on_delete=models.CASCADE,verbose_name='produit')
    annee = models.PositiveIntegerField(verbose_name='annee',choices=ANNEE_CHOICES,blank=True) 
    mois =  models.PositiveIntegerField(verbose_name='mois',choices=MOIS_CHOICES,null=True)  
    six_dernier_mois = models.JSONField(default=dict)
    value = models.PositiveIntegerField(verbose_name='Distr. moyenne mensuelle')
    def __str__(self):
        return f"{self.produit} - ({round(int(self.value)/12,0)})"

class DistrMoyReel(models.Model):
    ANNEE_CHOICES =(
        (2022,2022),
        (2021,2021),
        (2020,2022),
    )
    MOIS_CHOICES = (
        ('01','janvier'),
        ('02','Fevrier'),
        ('03','Mars'),
        ('04','Avril'),
        ('05','Mai'),
        ('06','Juin'),
        ('07','Juillet'),
        ('08','Aout'),
        ('09','Septembre'),
        ('10','Octobre'),
        ('11','Novembre'),
        ('12','Decembre'),

    )
    produit = models.ForeignKey(Produit,on_delete=models.CASCADE,verbose_name='produit')
    annee = models.PositiveIntegerField(verbose_name='annee',choices=ANNEE_CHOICES)
    mois = models.PositiveIntegerField(verbose_name='mois',choices=MOIS_CHOICES)
    value = models.PositiveIntegerField(verbose_name='Distr. moyenne annuelle')
    def __str__(self):
        return f"{self.produit} - ({round(int(self.value)/12,0)})"


class Partenaire(models.Model):    
    nom = models.CharField(max_length=255,verbose_name='Source')
    def __str__(self):
        return self.nom

class EtatCommande(models.Model):
    etat = models.CharField(max_length=255,verbose_name='Etat Commande')
    def __str__(self):
        return self.etat 
""" Le model Lot represente une commande"""  
class Commande(models.Model):     
   
    produit_commande = models.ForeignKey(Produit,on_delete=models.PROTECT,verbose_name='Produit',null=True)
    partenaire= models.ForeignKey(Partenaire,on_delete=models.PROTECT,verbose_name='partenaire',default=1)
    quantite_commande = models.PositiveIntegerField(verbose_name='quantite',null=True)
    prix_unitaire = models.PositiveIntegerField(verbose_name='prix unitaire(USD$)')
    date_livraison = models.DateField(verbose_name='Date livraison',null=True)
    #date_exp = models.DateField(verbose_name='Date exp.',null=True)
    lot_commande = models.CharField(max_length=500,verbose_name='lot',blank=True,null=True)
    observation = models.CharField(max_length=500,verbose_name='observation',blank=True,null=True)

    def __str__(self):
        return f"{self.partenaire} - {self.produit_commande} ({self.quantite_commande})"

class BonLivraison(models.Model):
    fournisseur = models.CharField(max_length=500,verbose_name='Fournisseur')
    num = models.CharField(max_length=255,verbose_name='Num lot')
    commande =models.ForeignKey(Commande,on_delete=models.CASCADE)    
    quantite = models.PositiveIntegerField(verbose_name='quantite')
    date_livraison =models.DateField(verbose_name='date livraison')
    date_exp = models.DateField(verbose_name='Date exp.',null=True)
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,)
    observation = models.CharField(max_length=500,verbose_name='observation',blank=True,null=True)

    def __str__(self):
        return f"{self.commande}"

class Sortie(models.Model):
    produit_sortie = models.ForeignKey(Produit,on_delete=models.PROTECT,verbose_name='produit',default=1)
    quantite_sortie = models.PositiveIntegerField(verbose_name='quantite')
    date_sortie =models.DateField(verbose_name='date sortie')
    lot_sortie = models.CharField(max_length=500,verbose_name='lot',blank=True,null=True)
    observation_sortie = models.CharField(max_length=500,verbose_name='observation',blank=True,null=True)
    def __str__(self):
        return f"{self.produit_sortie} ({self.quantite_sortie})"
        #return f"{self.num_lot} - {self.produit.designation} ({self.quantite})"

class InventaireSage(models.Model):
    MOIS_CHOICES = (
        ('01','janvier'),
        ('02','Fevrier'),
        ('03','Mars'),
        ('04','Avril'),
        ('05','Mai'),
        ('06','Juin'),
        ('07','Juillet'),
        ('08','Aout'),
        ('09','Septembre'),
        ('10','Octobre'),
        ('11','Novembre'),
        ('12','Decembre'),

    )
    ANNEE_CHOICES =(
        ('2022','2022'),
        ('2021','2021'),
        
    )
    produit_inventaire = models.ForeignKey(Produit,on_delete=models.CASCADE,verbose_name='Produit')  
    lot = models.CharField(max_length=255,null=True,blank=True)
    quantite_sage = models.PositiveIntegerField(verbose_name='quantite Sage')
    date_exp = models.DateField(verbose_name='Date exp.',null=True)
    prix_unitaire_sage = models.PositiveIntegerField(verbose_name="Prix Unitaire",default=0)
    mois = models.CharField(max_length=255,choices=MOIS_CHOICES)
    annee = models.CharField(max_length=255,choices=ANNEE_CHOICES)

    def get_absolute_url(self):
        return reverse('inventaire_list')

###########gestion Condom#####################################

medicaments/templates/medicaments/confirm_delete_modal.html
<!–Delete button will redirect to the href of the element with 'id = caller-id' property in this modal–>
<div class="modal " id="confirmDeleteModal" tabindex="-1" caller-id="" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <form action="{%url 'delete_commande' commande.pk %}" method="post" id="form_confirm">
        {% csrf_token %}
      <div class="modal-body confirm-delete">
        This is permanent
        <input type="hidden" value="{{commande.pk}}" name="commande_id">
        <p>Are you sure you want to delete "{{ commande }}"?</p>
        
        

        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal" id="confirmDeleteButtonModal" onclick="document.getElementById('form_confirm').submit();">Delete</button>
      </div>
    </form>
    </div>
  </div>
</div>

medicaments/templates/medicaments/delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

medicaments/templates/medicaments/dmm_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% block title %}APPMed{% endblock title %}

   {% block header %}
   <div class="header navbar">
    <div class="header-container">
        <div class="nav-logo">
            <a href="{% url 'home' %}">
                <div class="logo logo-dark" style="background-image: url({% static 'images/logo/abrema.jpg' %});"></div>
                <div class="logo logo-white" style="background-image: url({% static 'images/logo/logo-white.png' %});"></div>
            </a>
        </div>
        <ul class="nav-left">
            <li>
                <a class="sidenav-fold-toggler" href="javascript:void(0);">
                    <i class="mdi mdi-menu"></i>
                </a>
                <a class="sidenav-expand-toggler" href="javascript:void(0);">
                    <i class="mdi mdi-menu"></i>
                </a>
            </li>
        </ul>
        
        <!-- <img src="{% static 'images/logo/burundi.png' %} " alt="" class=""> -->
        <h3 class="m-v-10" style="text-align: center;">
            Gestion des medicaments
        </h3>
        
        
        <ul class="nav-right">
            <li class="m-r-10">
                <!--  right menu for login and profiles options-->
            </li>
        </ul>
    </div>
</div>
   {% endblock header %}


{% block pagecontainer %}
<div class="page-container p-l-5">
 

 {% block maincontent %}
 <div class="main-content">
    <div class="container-fluid m-l-0 p-l-0">
        <form method="post" id="dmm_form">
            {% csrf_token %}
           
            <div class="card col-6">
                <div class="card-header">
                    <h4 class="text-info">Distribution Moyenne Mensuelle: </h4>
                </div>
                <div class="card-body">
                    {{ form.non_form_errors }}
                    {{ form | crispy }} 
                <div class="row">
                    <div class="col-md-2">
                        <input type="checkbox" name="ajustement" id="ajustement" onclick="toggle('#six_dernier_mois',this);onload=toggle('#six_dernier_mois',this);">
                    </div>
                    <div class="col-md-4 m-b-20"><label for="ajustement">Ajuster</label></div>

                </div>  
                
<div id="six_dernier_mois" > 
<h4 class="text-info">Six derniers mois :</h4>
                
                    
                    <tbody>
                    <!-- insertion des six derniers mois avec ajax -->


                
                </tbody>
                 
</div>
                </div>
                 
                </div>
            </div>
            <div class="mt-3 mb-5">
                <button type="submit" class="px-5 btn btn-info">Sauvegarder</button>
                <button  class="px-5 btn btn-warning" onclick="history.go(-1);">Retour</button>
            </div>
            
        </form>
    </div>
</div>
 {%  endblock maincontent %}
 {% block footer%}
 <footer class="content-footer">
    <div class="footer">
        <div class="copyright">
            <span>Copyright © 2022 <b class="text-dark">Lopez</b>. All rights reserved.</span>
            
        </div>
    </div>
</footer>
 {% endblock footer%}
</div>

{% endblock pagecontainer %}


{% block js %}
    <script>
        function numAverage(a) {
            var b = a.length,
                c = 0, i;
            if(b!=0){
                for (i = 0; i < b; i++){
                c += Number(a[i]);
                }
                return c/b;
            }
            else{
                return 0;
            }
          }

        function toggle(idName, obj) {
        if ( !obj.checked ) $(idName).hide();
        else $(idName).show();
    } 

        $(document).ready(
            function(){  
        /** cascading categorie, produits*/             
        $("#id_categorie").change(function () {
           //console.log($(this));
            const categorie_id = $(this).val();  // get the selected subject ID from the HTML dropdown list 
            $.ajax({                       // initialize an AJAX request
                type: "POST",
                url: '{% url "get-products-ajax" %}',
                data: {
                    'categorie_id': categorie_id,       // add the country id to the POST parameters
                    'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),
                },
                success: function (data) {   // `data` is from `get_topics_ajax` view function
                    let html_data = '<option value="">---------</option>';
                    data.forEach(function (data) {
                        html_data += `<option value="${data.id}">${data.designation}</option>`
                    });
                    $("#id_produit").html(html_data); // replace the contents of the topic input with the data that came from the server
                }
            });
        });
        $("#ajustement").change(function(){
            if(this.checked){
                const produit = $("#id_produit").val()
                const mois = $("#id_mois").val()
                const annee = $("#id_annee").val()
                //alert(produit+mois+annee);
                if(produit =="" || mois =="" || annee==""){
                    alert("veuillez selectionner un produit");
                    this.checked = 0;
                }
                else{
                    //Ajax call
                    $.ajax({
                        type:"POST",
                        url:'{% url "get-ajax-dernier-six-mois" %}',
                        data:{
                            'produit':produit,
                            'mois':mois,
                            'annee':annee,
                            'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),
                        },
                        success: function(data){
                            html_data="";
                           // console.log(data); 
                            data.forEach(function (value,key) {
                                //console.log(value); 
                                var disabled = "";
                                if(value.value=='-'){
                                    var disabled = "disabled";
                                }  
                                html_data+= `<div class="row m-b-10">
                                    <div class="col-md-2"><input type="checkbox" name="ajuste_${value.mois}${value.annee}" id="ajuste_${value.mois}${value.annee}" class="form-control ajuste" ${disabled}></div>
                                    <div class="col-md-6"><label for="" class="form-label"></label>${value.mois_abbr} - ${value.annee} </div>
                                    <div class="col-md-4"><input type="text" id="dmm_${value.mois}${value.annee}" name="dmm_${value.mois}${value.annee}" class="form-control" value="${value.value}" disabled></div>
                                </div> `;
                               });
                               html_data+=`<div class="row m-b-10">                   
                                <div class="col-md-8"><strong>DMM ajusté : </strong></div>
                                <div class="col-md-4"><input type="text" id="dmm_ajuste" name="dmm_ajuste" class="form-control"  disabled></div>
                            </div>`;
                            $("#six_dernier_mois").html(html_data);
                            
                            $("input.ajuste").change(function(){
                                console.log("change");
                                var arr = [];
                                $('input.ajuste:checkbox:checked').each(function () {
                               
                                var id = $(this).attr('name').split("_")[1];
                                arr.push(parseInt($("#dmm_"+id).val().replace(",","")))
                               
                                    });
                                var moyenne = numAverage(arr);
                                $("#dmm_ajuste").val(moyenne);
                                $("#id_value").val(moyenne);
                                //console.log(moyenne);
                               
                            });

                        }
                    }

                    );

                    
                }

            }
           

        });
        $('#dmm_form').submit(function(){
            $("#dmm_form :disabled").removeAttr('disabled');
        });
        //calculer la moyenne des six derniers mois
        
       
   
    /////
    toggle($('#six_dernier_mois'),$('#ajustement'));
    }
        /** fin cascading categorie, produits*/  
        /** chargement des 6 derniers mois ajax call*/
        
        );

        /** fin chargement des 6 derniers mois ajax call*/

       
        

        ///cacher les 6 mois 
       
        </script>
{% endblock js%}

medicaments/templates/medicaments/produit_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}APPMed{% endblock title %}
   {% block header %}
   <div class="header navbar">
    <div class="header-container">
        <div class="nav-logo">
            <a href="{% url 'home' %}">
                <div class="logo logo-dark" style="background-image: url({% static 'images/logo/abrema.jpg' %});"></div>
                <div class="logo logo-white" style="background-image: url({% static 'images/logo/logo-white.png' %});"></div>
            </a>
        </div>
        <ul class="nav-left">
            <li>
                <a class="sidenav-fold-toggler" href="javascript:void(0);">
                    <i class="mdi mdi-menu"></i>
                </a>
                <a class="sidenav-expand-toggler" href="javascript:void(0);">
                    <i class="mdi mdi-menu"></i>
                </a>
            </li>
        </ul>
        
        <!-- <img src="{% static 'images/logo/burundi.png' %} " alt="" class=""> -->
        <h3 class="m-v-10" style="text-align: center;">
            Gestion des medicaments
        </h3>
        
        
        <ul class="nav-right">
            <li class="m-r-10">
                <!--  right menu for login and profiles options-->
            </li>
        </ul>
    </div>
</div>
   {% endblock header %}


{% block pagecontainer %}
<div class="page-container p-l-5">
 

 {% block maincontent %}
 <div class="main-content">
    <div class="container-fluid m-l-0 p-l-0">
        <form method="post">
            {% csrf_token %}
           
            <div class="card col-9">
                <div class="card-header">
                    <h4 class="text-info">Creation d un produit: </h4>
                </div>
                <div class="card-body">
                    {{ form.non_form_errors }}

                    
                    
                    <div class="row">
                        <div class="col-md-12">{{ form.designation | as_crispy_field }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.abbreviation | as_crispy_field }}</div>
                        <div class="col-md-6">{{ form.num_ref | as_crispy_field }}</div>

                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.programme | as_crispy_field }}</div>
                        <div class="col-md-6">{{ form.categorie | as_crispy_field }}</div>

                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.classification | as_crispy_field }}</div>
                        <div class="col-md-6">{{ form.conditionnement | as_crispy_field }}</div>

                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.dosage | as_crispy_field }}</div>
                        <div class="col-md-6">{{ form.formulation | as_crispy_field }}</div>

                    </div>
                    <div class="row">
                        <div class="col-md-6">{{ form.dashbord | as_crispy_field }}</div>                        

                    </div>
                    <div class="row">
                        {{ cout_unitaire_form_set.management_form|crispy }}
                       

                        {% for form in cout_unitaire_form_set %}
                           
                             <div class="col-md-2">{{ form.cout | as_crispy_field }}</div>
                            <div class="col-md-4">{{ form.date_debut | as_crispy_field }}</div>
                            <div class="col-md-4">{{ form.date_fin | as_crispy_field }}</div>
                            <!-- <div class="col-ms-2 m-t-30">
                                <label for="label-form">Delete</label>
                                <input type="checkbox" name="coutunitaire_set-{{ forloop.counter }}-DELETE" id="id_coutunitaire_set-{{ forloop.counter }}-DELETE">


                                <input type="hidden" name="coutunitaire_set-{{ forloop.counter }}-id" id="id_coutunitaire_set-{{ forloop.counter }}-id"><input type="hidden" name="coutunitaire_set-{{ forloop.counter }}-produit" id="id_coutunitaire_set-{{ forloop.counter }}-produit">
                            </div>  -->
                            {% if cout_unitaire_form_set.can_delete %}
                                <div class="col-md-2 m-t-30"> {{ form.DELETE | as_crispy_field }}</div>
                            {% endif %}
                            
                        {% endfor %}
                        {% for form in cout_unitaire_form_set %}
                            {% for hidden in form.hidden_fields%}
                                {{ hidden}}
                            {% endfor %}
                        {% endfor %}
                    </div>
                   
                    <!-- {% for form in cout_unitaire_form_set %}
                    {% crispy form %}
                    {% endfor %} -->
                    
    
                </div>
                 
                </div>
            </div>
            <div class="mt-3 mb-5">
                <button type="submit" class="px-5 btn btn-info">Sauvegarder</button>
                <button  class="px-5 btn btn-warning" onclick="history.go(-1);">Retour</button>
            </div>
            
        </form>
    </div>
</div>
 {%  endblock maincontent %}
 {% block footer%}
 <footer class="content-footer">
    <div class="footer">
        <div class="copyright">
            <span>Copyright © 2022 <b class="text-dark">Lopez</b>. All rights reserved.</span>
            
        </div>
    </div>
</footer>
 {% endblock footer%}
</div>

{% endblock pagecontainer %}


{% block js %}
    <script>
        $(document).ready(
            function(){               
        $("#id_categorie").change(function () {
            console.log($(this));
            const categorie_id = $(this).val();  // get the selected subject ID from the HTML dropdown list 
            $.ajax({                       // initialize an AJAX request
                type: "POST",
                url: '{% url "get-products-ajax" %}',
                data: {
                    'categorie_id': categorie_id,       // add the country id to the POST parameters
                    'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),
                },
                success: function (data) {   // `data` is from `get_topics_ajax` view function
                    let html_data = '<option value="">---------</option>';
                    data.forEach(function (data) {
                        html_data += `<option value="${data.id}">${data.designation}</option>`
                    });
                    $("#id_produit_commande").html(html_data); // replace the contents of the topic input with the data that came from the server
                }
            });
        });
        }
        )
        </script>
{% endblock js%}